import type { Metadata } from "next";
import { Geist, Geist_Mono,Raleway,Nunito } from "next/font/google";

import Header from "./components/Header";
import Footer from "./components/Footer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const nunito = Nunito({
  variable: "--font-nunito",

  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  
}) 
export const metadata: Metadata = {
  title: "Travulu ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
   
      <body
        className={` ${raleway.variable} ${geistSans.variable} ${geistMono.variable} ${nunito.variable} bg-white text-black dark:bg-black dark:text-white `}
      >
       
          <Header />
        <main className="pt-[85px] min-h-screen">
         
          {children}
         
        </main>

        <Footer />
      </body>
     
    </html>
  );
}
